# **IMPORTANDO BIBLIOTECAS**

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [ ]:
def extrair_dados():
    url = "https://books.toscrape.com/catalogue/page-1.html"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    livros = []

    for item in soup.find_all('article', class_='product_pod'):
        titulo = item.h3.a['title']
        preco = item.find('p', class_='price_color').text
        avaliacao = item.p['class'][1]

        livros.append([titulo, preco, avaliacao])

    return pd.DataFrame(livros, columns=['Título', 'Preco', 'Avaliação'])

print("dados extraidos")

dados extraidos

Extraindo Dados com Funçoes

In [ ]:
df_livros = extrair_dados()
print (df_livros)

                                               Título   Preco Avaliação
0                                A Light in the Attic  £51.77     Three
1                                  Tipping the Velvet  £53.74       One
2                                          Soumission  £50.10       One
3                                       Sharp Objects  £47.82      Four
4               Sapiens: A Brief History of Humankind  £54.23      Five
5                                     The Requiem Red  £22.65       One
6   The Dirty Little Secrets of Getting Your Dream...  £33.34      Four
7   The Coming Woman: A Novel Based on the Life of...  £17.93     Three
8   The Boys in the Boat: Nine Americans and Their...  £22.60      Four
9                                     The Black Maria  £52.15       One
10     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99       Two
11                              Shakespeare's Sonnets  £20.66      Four
12                                        Set Me Free  £17.46      Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29      Five
14                          Rip it Up and Start Again  £35.02      Five
15  Our Band Could Be Your Life: Scenes from the A...  £57.25     Three
16                                               Olio  £23.88       One
17  Mesaerion: The Best Science Fiction Stories 18...  £37.59       One
18                       Libertarianism for Beginners  £51.33       Two
19                            It's Only the Himalayas  £45.17       Two

In [ ]:
display(df_livros)

                                               Título   Preco Avaliação
0                                A Light in the Attic  £51.77     Three
1                                  Tipping the Velvet  £53.74       One
2                                          Soumission  £50.10       One
3                                       Sharp Objects  £47.82      Four
4               Sapiens: A Brief History of Humankind  £54.23      Five
5                                     The Requiem Red  £22.65       One
6   The Dirty Little Secrets of Getting Your Dream...  £33.34      Four
7   The Coming Woman: A Novel Based on the Life of...  £17.93     Three
8   The Boys in the Boat: Nine Americans and Their...  £22.60      Four
9                                     The Black Maria  £52.15       One
10     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99       Two
11                              Shakespeare's Sonnets  £20.66      Four
12                                        Set Me Free  £17.46      Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29      Five
14                          Rip it Up and Start Again  £35.02      Five
15  Our Band Could Be Your Life: Scenes from the A...  £57.25     Three
16                                               Olio  £23.88       One
17  Mesaerion: The Best Science Fiction Stories 18...  £37.59       One
18                       Libertarianism for Beginners  £51.33       Two
19                            It's Only the Himalayas  £45.17       Two

In [ ]:
df_livros.dtypes

Título       object
Preco        object
Avaliação    object
dtype: object

# **Conversão de Tipo**

A conversao de tipo é necessaria, pois objetos do tipo string, impedem operações aritimeticas

In [ ]:
#Limpeza do preço
df_livros['Preco'] = df_livros['Preco'].astype(str).str.replace('£', '').astype(float)

In [ ]:
df_livros

                                               Título  Preco Avaliação
0                                A Light in the Attic  51.77     Three
1                                  Tipping the Velvet  53.74       One
2                                          Soumission  50.10       One
3                                       Sharp Objects  47.82      Four
4               Sapiens: A Brief History of Humankind  54.23      Five
5                                     The Requiem Red  22.65       One
6   The Dirty Little Secrets of Getting Your Dream...  33.34      Four
7   The Coming Woman: A Novel Based on the Life of...  17.93     Three
8   The Boys in the Boat: Nine Americans and Their...  22.60      Four
9                                     The Black Maria  52.15       One
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99       Two
11                              Shakespeare's Sonnets  20.66      Four
12                                        Set Me Free  17.46      Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29      Five
14                          Rip it Up and Start Again  35.02      Five
15  Our Band Could Be Your Life: Scenes from the A...  57.25     Three
16                                               Olio  23.88       One
17  Mesaerion: The Best Science Fiction Stories 18...  37.59       One
18                       Libertarianism for Beginners  51.33       Two
19                            It's Only the Himalayas  45.17       Two

# **Comando .map**

In [ ]:
mapa_notas = {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
df_livros['Nota'] = df_livros['Avaliação'].map(mapa_notas)

`dropna()`

In [ ]:
#selecionando o que importa
df_livros_ml = df_livros[['Preco', 'Nota']].dropna()

In [ ]:
df_livros_ml.dtypes

Preco    float64
Nota       int64
dtype: object

In [ ]:
df_livros_ml_reindexado = df_livros_ml.reset_index(drop=True)
display(df_livros_ml_reindexado)

    Preco  Nota
0   51.77     3
1   53.74     1
2   50.10     1
3   47.82     4
4   54.23     5
5   22.65     1
6   33.34     4
7   17.93     3
8   22.60     4
9   52.15     1
10  13.99     2
11  20.66     4
12  17.46     5
13  52.29     5
14  35.02     5
15  57.25     3
16  23.88     1
17  37.59     1
18  51.33     2
19  45.17     2

In [ ]:
df_livros_ml_reindexado.index = df_livros_ml_reindexado.index + 1

display(df_livros_ml_reindexado)

    Preco  Nota
1   51.77     3
2   53.74     1
3   50.10     1
4   47.82     4
5   54.23     5
6   22.65     1
7   33.34     4
8   17.93     3
9   22.60     4
10  52.15     1
11  13.99     2
12  20.66     4
13  17.46     5
14  52.29     5
15  35.02     5
16  57.25     3
17  23.88     1
18  37.59     1
19  51.33     2
20  45.17     2

In [ ]:
print (df_livros_ml_reindexado)

    Preco  Nota
1   51.77     3
2   53.74     1
3   50.10     1
4   47.82     4
5   54.23     5
6   22.65     1
7   33.34     4
8   17.93     3
9   22.60     4
10  52.15     1
11  13.99     2
12  20.66     4
13  17.46     5
14  52.29     5
15  35.02     5
16  57.25     3
17  23.88     1
18  37.59     1
19  51.33     2
20  45.17     2

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
#Separando variavel (x= entrada, y= o que queremos prever)

X = df_livros_ml_reindexado[['Nota']]
y = df_livros_ml_reindexado['Preco']

In [ ]:
print (X)

    Nota
1      3
2      1
3      1
4      4
5      5
6      1
7      4
8      3
9      4
10     1
11     2
12     4
13     5
14     5
15     5
16     3
17     1
18     1
19     2
20     2

In [ ]:
print (X.values)

[[3]
 [1]
 [1]
 [4]
 [5]
 [1]
 [4]
 [3]
 [4]
 [1]
 [2]
 [4]
 [5]
 [5]
 [5]
 [3]
 [1]
 [1]
 [2]
 [2]]

In [ ]:
X_demonstracao =df_livros_ml_reindexado[['Nota', 'Nota']]
print(X_demonstracao.head())

   Nota  Nota
1     3     3
2     1     1
3     1     1
4     4     4
5     5     5

In [ ]:
from sklearn.model_selection import train_test_split
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(X_treino)

    Nota
9      4
6      1
12     4
4      4
19     2
17     1
14     5
3      1
10     1
20     2
5      5
13     5
8      3
11     2
15     5
7      4

In [ ]:
print(X_teste)

    Nota
1      3
18     1
16     3
2      1

In [ ]:
print (y_treino)

9     22.60
6     22.65
12    20.66
4     47.82
19    51.33
17    23.88
14    52.29
3     50.10
10    52.15
20    45.17
5     54.23
13    17.46
8     17.93
11    13.99
15    35.02
7     33.34
Name: Preco, dtype: float64

In [ ]:
print (y_teste)

1     51.77
18    37.59
16    57.25
2     53.74
Name: Preco, dtype: float64

regressao linear

In [ ]:
modelo = LinearRegression()
modelo.fit(X_treino, y_treino)

LinearRegression()

In [ ]:
#teste (predicao)
previsoes = modelo.predict((X_teste))
erro = mean_squared_error(y_teste, previsoes)

print(f"Modelo treinado! Erro : {erro: .2f}")

Modelo treinado! Erro :  281.98