In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
files.upload()

Saving notas alunos.csv to notas alunos.csv

{'notas alunos.csv': b'\xef\xbb\xbfNotas de Alunos;;;;;\r\nNomes;Nota 1 ;Nota 2;Nota 3;Nota 4;M\xc3\xa9dia\r\nPedro;4;7;7;3;5,5\r\nCarlos;5;4;8;4;4,5\r\nAna;6;5;4;5;5,0\r\nFabio;7;6;9;6;6,5\r\nPatricia;8;6;5;7;6,5\r\nMarcos;7;2;8;8;7,5\r\nSamuel;9;3;7;2;5,0\r\nKarol;7;3;5;1;4,0\r\nJose;8;6;2;2;4,0\r\nRodrigo;1;7;9;4;5,5\r\n'}

In [ ]:
dfnotas=pd.read_csv('notas alunos.csv', sep=';')

In [ ]:
print(dfnotas)

   Notas de Alunos Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
0            Nomes    Nota 1      Nota 2     Nota 3     Nota 4      Média
1            Pedro          4          7          7          3        5,5
2           Carlos          5          4          8          4        4,5
3              Ana          6          5          4          5        5,0
4            Fabio          7          6          9          6        6,5
5         Patricia          8          6          5          7        6,5
6           Marcos          7          2          8          8        7,5
7           Samuel          9          3          7          2        5,0
8            Karol          7          3          5          1        4,0
9             Jose          8          6          2          2        4,0
10         Rodrigo          1          7          9          4        5,5

In [ ]:
dfnotasarred=pd.read_csv('notas arredondadas.csv', sep=';')

In [ ]:
print(dfnotasarred)

   Notas de Alunos Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
0            Nomes    Nota 1      Nota 2     Nota 3     Nota 4      Média
1            Pedro          4          7          7          3          6
2           Carlos          5          4          8          4          5
3              Ana          6          5          4          5          5
4            Fabio          7          6          9          6          7
5         Patricia          8          6          5          7          7
6           Marcos          7          2          8          8          8
7           Samuel          9          3          7          2          5
8            Karol          7          3          5          1          4
9             Jose          8          6          2          2          4
10         Rodrigo          1          7          9          4          6

In [ ]:
vendas = pd.DataFrame({
    'data': ['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04'],
    'produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor'],
    'quantidade': [2, 15, 8, 3],
    'preco_unitario': [2500, 50, 180, 800],
    'categoria': ['Informática', 'Informática', 'Informática', 'Informática']})

In [ ]:
print(vendas)

         data   produto  quantidade  preco_unitario    categoria
0  2026-02-01  Notebook           2            2500  Informática
1  2026-02-02     Mouse          15              50  Informática
2  2026-02-03   Teclado           8             180  Informática
3  2026-02-04   Monitor           3             800  Informática

In [ ]:
vendas

         data   produto  quantidade  preco_unitario    categoria
0  2026-02-01  Notebook           2            2500  Informática
1  2026-02-02     Mouse          15              50  Informática
2  2026-02-03   Teclado           8             180  Informática
3  2026-02-04   Monitor           3             800  Informática

In [ ]:
vendas.shape

(4, 5)

In [ ]:
vendas.columns

Index(['data', 'produto', 'quantidade', 'preco_unitario', 'categoria'], dtype='object')

In [ ]:
vendas.dtypes

data              object
produto           object
quantidade         int64
preco_unitario     int64
categoria         object
dtype: object

In [ ]:
print (vendas['quantidade'].dtype)

int64

In [ ]:
vendas ['quantidade'] = vendas ['quantidade'].astype('int32')

In [ ]:
print (vendas['quantidade'].dtype)

int32

In [ ]:
vendas ['quantidade'] = vendas ['quantidade'].astype('float32')

In [ ]:
print (vendas['quantidade'].dtype)

float32

In [ ]:
vendas ['preco_unitario'].mean()

np.float64(882.5)

In [ ]:
vendas.describe()

       quantidade  preco_unitario
count    4.000000        4.000000
mean     7.000000      882.500000
std      5.944185     1126.894701
min      2.000000       50.000000
25%      2.750000      147.500000
50%      5.500000      490.000000
75%      9.750000     1225.000000
max     15.000000     2500.000000