Tratar dados 'tempo.csv'

* Aparencia: SOL, NUBLADO, CHUVA
* Temperatura: -130 ~ 130F
* Umidade: 0 ~ 100
* Jogar: sim/nao

tratar valores NAs

In [ ]:
import pandas as pd
import seaborn as srn
import statistics  as sts

In [ ]:
dataset = pd.read_csv("tempo.csv", sep=";")
dataset.head()

  Aparencia  Temperatura  Umidade       Vento Jogar
0       sol           85     85.0       FALSO   nao
1       sol           80     90.0  VERDADEIRO   nao
2   nublado           83     86.0       FALSO   sim
3     chuva           70      NaN       FALSO   sim
4     chuva           68     80.0       FALSO   sim

In [ ]:
agrupadoAparencia = dataset.groupby(['Aparencia']).size()
agrupadoAparencia

Aparencia
chuva      5
menos      1
nublado    3
sol        5
dtype: int64

In [ ]:
agrupadoTemperatura = dataset.groupby(['Temperatura']).size()
agrupadoTemperatura

Temperatura
64      1
65      1
68      1
69      1
70      1
71      1
72      1
75      2
80      1
81      1
83      1
85      1
1220    1
dtype: int64

In [ ]:
#estar entre 0 ~ 100
agrupamentoUmidade = dataset.groupby(['Umidade']).size()
agrupamentoUmidade

Umidade
65.0     1
70.0     3
75.0     1
80.0     1
85.0     1
86.0     1
90.0     2
91.0     1
95.0     1
200.0    1
dtype: int64

In [ ]:
#Vento
agrupamentoVento = dataset.groupby(['Vento']).size()
agrupamentoVento

Vento
FALSO         7
VERDADEIRO    6
dtype: int64

In [ ]:
#Jogar
agrupamentoJogar = dataset.groupby(['Jogar']).size()
agrupamentoJogar

Jogar
nao    5
sim    9
dtype: int64

In [ ]:
dataset.isnull().sum()

Aparencia      0
Temperatura    0
Umidade        1
Vento          1
Jogar          0
dtype: int64

In [ ]:
dataset['Umidade'] = dataset['Umidade'].astype(float)
agrupamentoUmidade

Umidade
65.0     1
70.0     3
75.0     1
80.0     1
85.0     1
86.0     1
90.0     2
91.0     1
95.0     1
200.0    1
dtype: int64

In [ ]:
dataset['Temperatura'] = dataset['Temperatura'].astype(float)
agrupadoTemperatura

Temperatura
64      1
65      1
68      1
69      1
70      1
71      1
72      1
75      2
80      1
81      1
83      1
85      1
1220    1
dtype: int64

In [ ]:
dataset.head()

  Aparencia  Temperatura  Umidade       Vento Jogar
0       sol         85.0     85.0       FALSO   nao
1       sol         80.0     90.0  VERDADEIRO   nao
2   nublado         83.0     86.0       FALSO   sim
3     chuva         70.0      NaN       FALSO   sim
4     chuva         68.0     80.0       FALSO   sim

In [ ]:
# Aparencia Temperatura	Umidade	Vento	Jogar

dataset['Umidade'].describe()

count     13.000000
mean      89.769231
std       34.540203
min       65.000000
25%       70.000000
50%       85.000000
75%       90.000000
max      200.000000
Name: Umidade, dtype: float64

In [ ]:
mediana = sts.median(dataset['Umidade'])
mediana

85.5

In [ ]:
dataset['Umidade'].fillna(mediana,inplace=True)

/tmp/ipykernel_16792/1006238390.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Umidade'].fillna(mediana,inplace=True)

In [ ]:
dataset['Umidade'].isnull().sum()

np.int64(0)

In [ ]:
print(dataset['Vento'].apply(type).value_counts())

Vento
<class 'str'>      13
<class 'float'>     1
Name: count, dtype: int64

In [ ]:
dataset['Vento']

0          FALSO
1     VERDADEIRO
2          FALSO
3          FALSO
4          FALSO
5     VERDADEIRO
6     VERDADEIRO
7          FALSO
8          FALSO
9            NaN
10    VERDADEIRO
11    VERDADEIRO
12         FALSO
13    VERDADEIRO
Name: Vento, dtype: object

In [ ]:
dataset['Vento'].fillna('FALSO',inplace=True)

In [ ]:
dataset['Vento'].isnull().sum()

np.int64(0)

In [ ]:
#Temperatura fora do dominio -130 ~ 130F

dataset['Temperatura'].max()

1220.0

In [ ]:
dataset.loc[(dataset['Temperatura'] <  -130 )  | ( dataset['Temperatura'] >  130) ]

  Aparencia  Temperatura  Umidade  Vento Jogar
7       sol       1220.0     95.0  FALSO   nao

In [ ]:
medianaTemper = sts.median(dataset['Temperatura'])
medianaTemper

73.5

In [ ]:
dataset.loc[(dataset['Temperatura'] <  -130 )  | ( dataset['Temperatura'] >  130) , 'Temperatura' ]=medianaTemper
dataset.loc[(dataset['Temperatura'] <  -130 )  | ( dataset['Temperatura'] >  130) ]

Empty DataFrame
Columns: [Aparencia, Temperatura, Umidade, Vento, Jogar]
Index: []

In [ ]:
#Umidade: 0 ~ 100
dataset['Temperatura'].head()

0    85.0
1    80.0
2    83.0
3    70.0
4    68.0
Name: Temperatura, dtype: float64

In [ ]:
agrupamentoUmidade

Umidade
65.0     1
70.0     3
75.0     1
80.0     1
85.0     1
86.0     1
90.0     2
91.0     1
95.0     1
200.0    1
dtype: int64

In [ ]:
dataset.loc[(dataset['Umidade']<0) | (dataset['Umidade']>100)]

  Aparencia  Temperatura  Umidade  Vento Jogar
9     chuva         75.0    200.0  FALSO   sim

In [ ]:
medianaUmidade= sts.median(dataset['Umidade'])
medianaUmidade

85.25

In [ ]:
dataset.loc[(dataset['Umidade']<0) | (dataset['Umidade']>100), 'Umidade'] = medianaUmidade
dataset.loc[(dataset['Umidade']<0) | (dataset['Umidade']>100)]

Empty DataFrame
Columns: [Aparencia, Temperatura, Umidade, Vento, Jogar]
Index: []

In [ ]:
dataset.head()

  Aparencia  Temperatura  Umidade       Vento Jogar
0       sol         85.0     85.0       FALSO   nao
1       sol         80.0     90.0  VERDADEIRO   nao
2   nublado         83.0     86.0       FALSO   sim
3     chuva         70.0     85.5       FALSO   sim
4     chuva         68.0     80.0       FALSO   sim

In [ ]:
dataset

   Aparencia  Temperatura  Umidade       Vento Jogar
0        sol         85.0    85.00       FALSO   nao
1        sol         80.0    90.00  VERDADEIRO   nao
2    nublado         83.0    86.00       FALSO   sim
3      chuva         70.0    85.50       FALSO   sim
4      chuva         68.0    80.00       FALSO   sim
5      chuva         65.0    70.00  VERDADEIRO   nao
6      menos         64.0    65.00  VERDADEIRO   sim
7        sol         73.5    95.00       FALSO   nao
8        sol         69.0    70.00       FALSO   sim
9      chuva         75.0    85.25       FALSO   sim
10       sol         75.0    70.00  VERDADEIRO   sim
11   nublado         72.0    90.00  VERDADEIRO   sim
12   nublado         81.0    75.00       FALSO   sim
13     chuva         71.0    91.00  VERDADEIRO   nao

In [ ]:

dataset.dtypes

Aparencia       object
Temperatura    float64
Umidade        float64
Vento           object
Jogar           object
dtype: object